sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anishsinha1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anishsinha1/docker-react yarn test --coverage
